import Head from 'next/head'

import Navbar from '../components/Navbar/Navbar'
import HeroSection from '../components/HeroSection/HeroSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Davean</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <HeroSection />
    </>
  )
}
