import Head from 'next/head'

import Navbar from '../components/Navbar/Navbar'
import HeroSection from '../components/HeroSection/HeroSection'
import Frase from '../components/Frase/Frase'
import Catalogo from '../components/Catalogo/Catalogo'
import Plazas from '../components/Plazas/Plazas'
import Packs from '../components/Packs/Packs'
import Preguntas from '../components/Preguntas/Preguntas'
import Reviews from '../components/Reviews/Reviews'
import Footer from '../components/Footer/Footer'

import { Suspense, useEffect, useRef, useState } from 'react'

import Loading from './loading'

export default function Home() {

  const header = useRef(null)
  const catalogo = useRef(null)
  const packs = useRef(null)
  const preguntas = useRef(null)

  const [isMobile, setMobile] = useState(false)

  useEffect(() => {
    setMobile(window.innerWidth <= 769)
    window.addEventListener('resize', () => {
      setMobile(window.innerWidth <= 769)
    })
  }, [])

  return (
    <>
      <Head>
        <title>Davean Comuniones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        
        {/* Preload fonts to load fonts faster */}
        <link
          rel="preload"
          href="/fonts/adele-light-webfont-webfont.woff"
          as="font"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/adele-light-webfont-webfont.woff2"
          as="font"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/dk_lemon_yellow_sun-webfont.woff"
          as="font"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/dk_lemon_yellow_sun-webfont.woff2"
          as="font"
          crossOrigin="anonymous"modernline-webfont
        />
        <link
          rel="preload"
          href="/fonts/modernline-webfont.woff"
          as="font"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/modernline-webfont.woff2"
          as="font"
          crossOrigin="anonymous"
        />
      </Head>

      <Suspense fallback={<Loading />}>
        <Navbar catalogo={catalogo} packs={packs} preguntas={preguntas}/>

        <main>
          <HeroSection header={header}/>

          <Frase />

          <Catalogo isMobile={isMobile} catalogo={catalogo}/>

          <Plazas isMobile={isMobile}/>

          <Packs isMobile={isMobile} packs={packs}/>

          <Preguntas isMobile={isMobile} preguntas={preguntas}/>

          <Reviews isMobile={isMobile}/>
        </main>
        
        <Footer header={header}/>
      </Suspense>
    </>
  )
}
