import Head from 'next/head'

import Navbar from '../components/Navbar/Navbar'
import HeroSection from '../components/HeroSection/HeroSection'
import Frase from '../components/Frase/Frase'
import Catalogo from '../components/Catalogo/Catalogo'
import Plazas from '../components/Plazas/Plazas'
import Packs from '../components/Packs/Packs'
import Preguntas from '../components/Preguntas/Preguntas'
import Reviews from '../components/Reviews/Reviews'
import Footer from '../components/Footer/Footer'

import { useEffect, useRef, useState } from 'react'

export default function Home() {

  const header = useRef(null)
  const catalogo = useRef(null)
  const packs = useRef(null)
  const preguntas = useRef(null)

  const [isMobile, setMobile] = useState(false)

  useEffect(() => {
    setMobile(window.innerWidth <= 769)
    window.addEventListener('resize', () => {
      setMobile(window.innerWidth <= 769)
    })
  }, [])

  return (
    <>
      <Head>
        <title>Davean</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar catalogo={catalogo} packs={packs} preguntas={preguntas}/>

      <main>
        <HeroSection header={header}/>

        <Frase />

        <Catalogo isMobile={isMobile} catalogo={catalogo}/>

        <Plazas isMobile={isMobile}/>

        <Packs isMobile={isMobile} packs={packs}/>

        <Preguntas isMobile={isMobile} preguntas={preguntas}/>

        <Reviews isMobile={isMobile}/>
      </main>
      
      <Footer header={header}/>
    </>
  )
}
